/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.view;
import br.edu.ifsul.cc.lpoo.dao.PersistenciaJPA;
import br.edu.ifsul.cc.lpoo.model.Alunos;
import br.edu.ifsul.cc.lpoo.model.Disciplinas;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author 20221PF.CC0003
 */
public class TelaAlunosEdit extends javax.swing.JDialog {

    private Alunos aluno;
    
    /**
     * Creates new form TelaAlunosEdit1
     */
       //Especificação Trabalho: 
        //Cadastro Aluno, Professor e Disciplina. 
        //ComboBox Aluno seleciona Discplina.  
        //ComboBox Disciplina seleciona Professor. 
        //CRUD de todos.
    
    public TelaAlunosEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void listarProfessores() {
        cmbDisciplinas.removeAllItems();
        PersistenciaJPA jpa = new PersistenciaJPA();
        jpa.conexaoAberta();
        List<Disciplinas> lista = jpa.getDisciplinas();

        for (Disciplinas o : lista) {
            cmbDisciplinas.addItem(o);
        }

        jpa.fecharConexao();
    }

     public void setAlunos(Alunos aluno) {   
        this.aluno = aluno;
        txtIDAluno.setText(aluno.getId() != null ? aluno.getId().toString() : "");
        txtNomeAluno.setText(aluno.getNome());
        cmbDisciplinas.getModel().setSelectedItem(aluno.getDisciplina().getNomeDisciplina());
        listarProfessores();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAlunos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbDisciplinas = new javax.swing.JComboBox<>();
        txtIDAluno = new javax.swing.JTextField();
        txtNomeAluno = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();

        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("ID Aluno");

        jLabel2.setText("ID");

        jLabel3.setText("Nome Aluno");

        jLabel4.setText("Disciplina");

        txtIDAluno.setEditable(false);

        btnSalvar.setText("SALVAR ALTERAÇÃO");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancelar");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogAlunosLayout = new javax.swing.GroupLayout(dialogAlunos);
        dialogAlunos.setLayout(dialogAlunosLayout);
        dialogAlunosLayout.setHorizontalGroup(
            dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAlunosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogAlunosLayout.createSequentialGroup()
                            .addComponent(btnSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancela))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogAlunosLayout.createSequentialGroup()
                            .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIDAluno)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(51, 51, 51)
                            .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogAlunosLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );
        dialogAlunosLayout.setVerticalGroup(
            dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAlunosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtIDAluno))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancela))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(dialogAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogAlunosLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jLabel2)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );

        getContentPane().add(dialogAlunos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        SalvaAluno();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void SalvaAluno() {
        
            PersistenciaJPA jpa = new PersistenciaJPA();
            try {
                jpa.conexaoAberta();
                Alunos modaJPA = (Alunos) jpa.find(Alunos.class, aluno.getId());
                modaJPA.setNome(txtNomeAluno.getText());

                Disciplinas disc = (Disciplinas) cmbDisciplinas.getSelectedItem();
                modaJPA.setDisciplina(disc);

                jpa.persist(modaJPA);
                jpa.fecharConexao();
                dispose();
            } catch (Exception e) {
                System.err.println("Erro ao salvar aluno!");
                
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAlunosEdit dialog = new TelaAlunosEdit(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Disciplinas> cmbDisciplinas;
    private javax.swing.JPanel dialogAlunos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtIDAluno;
    private javax.swing.JTextField txtNomeAluno;
    // End of variables declaration//GEN-END:variables
}
